name: ElyRestorer
version: ${project.version}
main: me.subkek.elyrestorer.ElyRestorer
authors: ['sub-kek']
api-version: 1.16
load: POSTWORLD
description: 'The simple skin system plugin uses ElyBy. Written by subkek.'
website: 'https://github.com/sub-kek'